---
name: Smartphoton
version: 1.0
slug: smartphoton
description: Smartphoton JK-BMS via RS485
url: https://domosimple.eu/forum
ingress: false
#ingress_port: 1870
ingress_stream: false
panel_icon: mdi:sitemap
init: false
homeassistant: 2021.3.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  1870/tcp: 1870
ports_description:
  1870/tcp: Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
options:
  Broker_IP: localhost
  Broker_Password: 12345678
  Broker_Port: 1883
  Broker_User: administrateur
  Number_of_BMS: 1
  USB_serial_port: /dev/ttyUSB0
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  Broker_IP: str
  Broker_Password: password?
  Broker_Port: port?
  Broker_User: str
  Number_of_BMS: str
  USB_serial_port: list(/dev/ttyUSB0|/dev/ttyUSB1)
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  not_need: "str?"
  leave_front_door_open: bool?
  safe_mode: bool?
  max_old_space_size: int?
